name: Daily Quote Bot

on:
  schedule:
    - cron: '0 9 * * *'
    - cron: '0 13 * * *'
    - cron: '0 17 * * *'
    - cron: '0 21 * * *'
  workflow_dispatch:

permissions:
  contents: write  # ✅ Required to push changes back to the repo

jobs:
  send-daily-quote:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run daily quote bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        echo "Starting daily quote bot check..."
        python daily_quote_bot.py
        echo "Bot execution completed."

    - name: Set up Git for commit
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit last quote hash
      run: |
        git add last_quote_data.json
        git commit -m "Update last sent quote hash" || echo "No changes to commit"
        git push origin main

    - name: Show completion status
      if: always()
      run: |
        echo "Workflow completed at $(date)"
