name: Daily Quote Bot

on:
  schedule:
    - cron: '0 9 * * *'   # 9:00 AM UTC
    - cron: '0 13 * * *'  # 1:00 PM UTC
    - cron: '0 17 * * *'  # 5:00 PM UTC
    - cron: '0 21 * * *'  # 9:00 PM UTC
  workflow_dispatch: # manual trigger

jobs:
  send-daily-quote:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Ensure default last_quote_data.json exists
      run: |
        echo '{}' > last_quote_data.json

    - name: Try to download previous state
      uses: actions/download-artifact@v4
      with:
        name: quote-state
        path: .
      continue-on-error: true  # allow it to fail silently on first run

    - name: Run Daily Quote Bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python daily_quote_bot.py

    - name: Upload state file for next run
      uses: actions/upload-artifact@v4
      with:
        name: quote-state
        path: last_quote_data.json

    - name: Show completion status
      if: always()
      run: echo "✅ Daily quote bot completed at $(date)"
