name: Daily Quote Bot

on:
  schedule:
    - cron: '0 9 * * *'
    - cron: '0 13 * * *'
    - cron: '0 17 * * *'
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  send-daily-quote:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Create default state if missing
      run: |
        if [ ! -f last_quote_data.json ]; then echo '{}' > last_quote_data.json; fi

    - name: Try to download last quote state
      uses: actions/download-artifact@v4
      with:
        name: quote-state
        path: .
      continue-on-error: true

    - name: Run the bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python daily_quote_bot.py

    - name: Upload latest quote state
      uses: actions/upload-artifact@v4
      with:
        name: quote-state
        path: last_quote_data.json
