name: Daily Quote Bot
on:
  schedule:
    # Run 4 times a day: 9 AM, 1 PM, 5 PM, 9 PM UTC
    - cron: '0 9 * * *'   # 9 AM UTC
    - cron: '0 13 * * *'  # 1 PM UTC  
    - cron: '0 17 * * *'  # 5 PM UTC
    - cron: '0 21 * * *'  # 9 PM UTC
  workflow_dispatch:      # Allow manual triggering

jobs:
  send-daily-quote:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # Need write permission for git operations
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0    # Fetch full history
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4
    
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Pull latest changes
      run: |
        git pull origin main || true
    
    - name: Create default state if missing
      run: |
        if [ ! -f last_quote_data.json ]; then 
          echo '{"hash": "", "date": "", "title": "", "sent_at": "", "fetch_date": ""}' > last_quote_data.json
        fi
    
    - name: Run the bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python daily_quote_bot.py
    
    - name: Commit and push state file if changed
      run: |
        if [ -f last_quote_data.json ]; then
          git add last_quote_data.json
          if ! git diff --staged --quiet; then
            git commit -m "Update last_quote_data.json - $(date)"
            git push origin main
          else
            echo "No changes to commit"
          fi
        fi
      continue-on-error: true
